name: JS Actions
on:
  issues:
  types: [opened, edited, milestoned]
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: hello-action
      uses: ./.github/actions/hello-world
